# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='buf.proto',
  package='buf',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tbuf.proto\x12\x03\x62uf\")\n\x0cSolveRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0b\n\x03img\x18\x02 \x03(\x0c\" \n\rSolveResponse\x12\x0f\n\x07\x61nswers\x18\x01 \x03(\x08\"\x19\n\tHiRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\nHiResponse\x12\x10\n\x08response\x18\x01 \x01(\t2k\n\x0eSolverServicer\x12\x30\n\x05Solve\x12\x11.buf.SolveRequest\x1a\x12.buf.SolveResponse\"\x00\x12\'\n\x02Hi\x12\x0e.buf.HiRequest\x1a\x0f.buf.HiResponse\"\x00\x62\x06proto3'
)




_SOLVEREQUEST = _descriptor.Descriptor(
  name='SolveRequest',
  full_name='buf.SolveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='buf.SolveRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='img', full_name='buf.SolveRequest.img', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=59,
)


_SOLVERESPONSE = _descriptor.Descriptor(
  name='SolveResponse',
  full_name='buf.SolveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='answers', full_name='buf.SolveResponse.answers', index=0,
      number=1, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=93,
)


_HIREQUEST = _descriptor.Descriptor(
  name='HiRequest',
  full_name='buf.HiRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='buf.HiRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=120,
)


_HIRESPONSE = _descriptor.Descriptor(
  name='HiResponse',
  full_name='buf.HiResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='buf.HiResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['SolveRequest'] = _SOLVEREQUEST
DESCRIPTOR.message_types_by_name['SolveResponse'] = _SOLVERESPONSE
DESCRIPTOR.message_types_by_name['HiRequest'] = _HIREQUEST
DESCRIPTOR.message_types_by_name['HiResponse'] = _HIRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SolveRequest = _reflection.GeneratedProtocolMessageType('SolveRequest', (_message.Message,), {
  'DESCRIPTOR' : _SOLVEREQUEST,
  '__module__' : 'buf_pb2'
  # @@protoc_insertion_point(class_scope:buf.SolveRequest)
  })
_sym_db.RegisterMessage(SolveRequest)

SolveResponse = _reflection.GeneratedProtocolMessageType('SolveResponse', (_message.Message,), {
  'DESCRIPTOR' : _SOLVERESPONSE,
  '__module__' : 'buf_pb2'
  # @@protoc_insertion_point(class_scope:buf.SolveResponse)
  })
_sym_db.RegisterMessage(SolveResponse)

HiRequest = _reflection.GeneratedProtocolMessageType('HiRequest', (_message.Message,), {
  'DESCRIPTOR' : _HIREQUEST,
  '__module__' : 'buf_pb2'
  # @@protoc_insertion_point(class_scope:buf.HiRequest)
  })
_sym_db.RegisterMessage(HiRequest)

HiResponse = _reflection.GeneratedProtocolMessageType('HiResponse', (_message.Message,), {
  'DESCRIPTOR' : _HIRESPONSE,
  '__module__' : 'buf_pb2'
  # @@protoc_insertion_point(class_scope:buf.HiResponse)
  })
_sym_db.RegisterMessage(HiResponse)



_SOLVERSERVICER = _descriptor.ServiceDescriptor(
  name='SolverServicer',
  full_name='buf.SolverServicer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=154,
  serialized_end=261,
  methods=[
  _descriptor.MethodDescriptor(
    name='Solve',
    full_name='buf.SolverServicer.Solve',
    index=0,
    containing_service=None,
    input_type=_SOLVEREQUEST,
    output_type=_SOLVERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Hi',
    full_name='buf.SolverServicer.Hi',
    index=1,
    containing_service=None,
    input_type=_HIREQUEST,
    output_type=_HIRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SOLVERSERVICER)

DESCRIPTOR.services_by_name['SolverServicer'] = _SOLVERSERVICER

# @@protoc_insertion_point(module_scope)
